"""empty message

Revision ID: 2f0ee09afbab
Revises: 8a20b2a49bff
Create Date: 2019-06-18 14:36:30.676545

"""

# revision identifiers, used by Alembic.
revision = '2f0ee09afbab'
down_revision = '8a20b2a49bff'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
