"""empty message

Revision ID: 8a20b2a49bff
Revises: 9c72a953421c
Create Date: 2019-06-18 09:48:08.241604

"""

# revision identifiers, used by Alembic.
revision = '8a20b2a49bff'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
