"""empty message

Revision ID: a082676043c4
Revises: bf7e87acb489
Create Date: 2019-06-21 07:35:18.462990

"""

# revision identifiers, used by Alembic.
revision = 'a082676043c4'
down_revision = 'bf7e87acb489'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('first_name', sa.String(length=300), nullable=False),
    sa.Column('last_name', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('director', sa.String(length=300), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name', 'title', 'director')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
