"""empty message

Revision ID: bf7e87acb489
Revises: 2f0ee09afbab
Create Date: 2019-06-18 14:39:19.479624

"""

# revision identifiers, used by Alembic.
revision = 'bf7e87acb489'
down_revision = '2f0ee09afbab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
